const getControlOption = require('./control');
const Random = require('mockjs').Random;

module.exports.presetCols = [{
  id: 'productImg',
  name: '商品图片',
  colType: 'FormPhoto',
  controlOptions: getControlOption('FormPhoto'),
  visibility: true,
  sortRank: 10,
  valueType: 'image',
  width: Random.integer(90, 350),
  summary: null
}, {
  id: 'productName',
  name: '商品名称',
  colType: 'FormTextBox',
  controlOptions: getControlOption('FormTextBox'),
  visibility: true,
  sortRank: 20,
  valueType: 'string',
  width: Random.integer(90, 350),
  summary: null,
}, {
  id: 'storeKeeper',
  name: '库管',
  colType: 'FormUser',
  controlOptions: getControlOption('FormUser'),
  visibility: true,
  sortRank: 30,
  valueType: 'user',
  width: Random.integer(90, 350),
  summary: null,
}, {
  id: 'expenseDepart333333',
  name: '报销部门',
  colType: 'FormDepartment',
  controlOptions: getControlOption('FormDepartment'),
  visibility: true,
  sortRank: 40,
  valueType: 'depart',
  width: Random.integer(90, 350),
  summary: null,
}, {
  id: 'expenseDetail',
  name: '费用明细',
  colType: 'FormGridView',
  controlOptions: getControlOption('FormGridView'),
  visibility: true,
  sortRank: 50,
  valueType: 'grid',
  width: Random.integer(90, 350),
  summary: null,
},
// {
//   id: 'storeAddress',
//   name: '仓库地址',
//   colType: 'FormAreaSelect',
//   controlOptions: getControlOption('FormAreaSelect'),
//   visibility: true,
//   sortRank: 60,
//   valueType: 'string',
//   width: Random.integer(90, 200),
//   summary: null,
// },
{
  id: 'price',
  name: '价格',
  colType: 'FormNumber',
  controlOptions: getControlOption('FormNumber'),
  visibility: true,
  sortRank: 70,
  valueType: 'number',
  width: Random.integer(90, 350),
  summary: null,
}, {
  id: 'brand',
  name: '品牌',
  colType: 'FormDropDownList',
  controlOptions: getControlOption('FormDropDownList'),
  visibility: true,
  sortRank: 80,
  valueType: 'string',
  width: Random.integer(90, 350),
  summary: null,
}, {
  id: 'onSaleTime',
  name: '上架时间',
  colType: 'FormDateTime',
  controlOptions: getControlOption('FormDateTime'),
  visibility: true,
  sortRank: 90,
  valueType: 'date',
  width: Random.integer(90, 350),
  summary: null,
}, {
  id: 'description',
  name: '描述',
  colType: 'FormTextArea',
  controlOptions: getControlOption('FormTextArea'),
  visibility: true,
  sortRank: 100,
  valueType: 'string',
  width: Random.integer(90, 350),
  summary: null,
}, {
  id: 'categoryChoose',
  name: '类目',
  colType: 'FormCheckboxList',
  controlOptions: getControlOption('FormCheckboxList'),
  visibility: true,
  sortRank: 110,
  valueType: 'array',
  width: Random.integer(90, 350),
  summary: null,
}, {
  id: 'level',
  name: '档次',
  colType: 'FormDropDownList',
  controlOptions: getControlOption('FormDropDownList'),
  visibility: true,
  sortRank: 120,
  valueType: 'string',
  width: Random.integer(90, 350),
  summary: null,
}, {
  id: 'listFile',
  name: '清单文件',
  colType: 'FormAttachment',
  controlOptions: getControlOption('FormAttachment'),
  visibility: true,
  sortRank: 130,
  valueType: 'file',
  width: Random.integer(90, 350),
  summary: null,
}];
